workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - 3qzemra65r5o@mail.ru
